apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      serviceAccountName: emailservice
      terminationGracePeriodSeconds: 5
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: server
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        image: {{ .Values.services.emailservice.image.repository }}:{{ .Values.services.emailservice.image.tag | default .Values.global.imageTag }}
        ports:
        - containerPort: {{ .Values.services.emailservice.port }}
        env:
        - name: PORT
          value: "{{ .Values.services.emailservice.port }}"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.services.emailservice.port }}
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.services.emailservice.port }}
        resources:
          {{- toYaml .Values.services.emailservice.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - name: grpc
    port: {{ .Values.services.emailservice.servicePort }}
    targetPort: {{ .Values.services.emailservice.port }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice