apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: {{ .Values.services.loadgenerator.replicas }}
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: loadgenerator
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      initContainers:
      - command:
        - /bin/sh
        - -exc
        - |
          MAX_RETRIES=12
          RETRY_INTERVAL=10
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
            STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
            if [ $STATUSCODE -eq 200 ]; then
                echo "Frontend is reachable."
                exit 0
            fi
            echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
            sleep $RETRY_INTERVAL
          done
          echo "Failed to reach frontend after $MAX_RETRIES attempts."
          exit 1
        name: frontend-check
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        image: busybox:latest
        env:
        - name: FRONTEND_ADDR
          value: "frontend:80"
      containers:
      - name: main
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        image: {{ .Values.services.loadgenerator.image.repository }}:{{ .Values.services.loadgenerator.image.tag | default .Values.global.imageTag }}
        env:
        - name: FRONTEND_ADDR
          value: "frontend:80"
        - name: USERS
          value: "{{ .Values.services.loadgenerator.users }}"
        - name: RATE
          value: "{{ .Values.services.loadgenerator.rate }}"
        resources:
          {{- toYaml .Values.services.loadgenerator.resources | nindent 10 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgenerator