apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      serviceAccountName: productcatalogservice
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 5
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: server
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        image: {{ .Values.services.productcatalogservice.image.repository }}:{{ .Values.services.productcatalogservice.image.tag | default .Values.global.imageTag }}
        ports:
        - containerPort: {{ .Values.services.productcatalogservice.port }}
        env:
        - name: PORT
          value: "{{ .Values.services.productcatalogservice.port }}"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: {{ .Values.services.productcatalogservice.port }}
        livenessProbe:
          grpc:
            port: {{ .Values.services.productcatalogservice.port }}
        resources:
          {{- toYaml .Values.services.productcatalogservice.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: {{ .Values.services.productcatalogservice.port }}
    targetPort: {{ .Values.services.productcatalogservice.port }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice