services:
  adservice:
    image:
      repository: ghcr.io/amadidominic15/adservice
      tag: "18435534623"
    port: 9555
    resources:
      requests:
        cpu: 200m
        memory: 180Mi
      limits:
        cpu: 300m
        memory: 300Mi
  cartservice:
    image:
      repository: ghcr.io/amadidominic15/cartservice
      tag: "latest"
    port: 7070
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 300m
        memory: 128Mi
  checkoutservice:
    image:
      repository: ghcr.io/amadidominic15/checkoutservice
      tag: "latest"
    port: 5050
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  currencyservice:
    image:
      repository: ghcr.io/amadidominic15/currencyservice
      tag: "latest"
    port: 7000
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  emailservice:
    image:
      repository: ghcr.io/amadidominic15/emailservice
      tag: "18522153893"
    port: 8080
    servicePort: 5000
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  frontend:
    image:
      repository: ghcr.io/amadidominic15/frontend
      tag: "latest"
    port: 8080
    serviceType: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  loadgenerator:
    image:
      repository: ghcr.io/amadidominic15/loadgenerator
      tag: "latest"
    replicas: 1
    users: "10"
    rate: "1"
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  paymentservice:
    image:
      repository: ghcr.io/amadidominic15/paymentservice
      tag: "latest"
    port: 50051
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  productcatalogservice:
    image:
      repository: ghcr.io/amadidominic15/productcatalogservice
      tag: "latest"
    port: 3550
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  recommendationservice:
    image:
      repository: ghcr.io/amadidominic15/recommendationservice
      tag: "latest"
    port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 220Mi
      limits:
        cpu: 200m
        memory: 450Mi
  shippingservice:
    image:
      repository: ghcr.io/amadidominic15/shippingservice
      tag: "latest"
    port: 50051
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
redis:
  image: redis:alpine
  port: 6379
  resources:
    requests:
      cpu: 70m
      memory: 200Mi
    limits:
      cpu: 125m
      memory: 256Mi
securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
dockerregistry:
  enabled: false
ingress:
  enabled: true
  name: online-boutique
  className: nginx
  ssl-redirect: "true"
  host: www.online-boutique.com
