name: BUILD SCAN PUSH AND UPDATE IMAGE FOR CARTSERVICE

on:
  push:
    branches:
      - main
    paths:
      - 'cartservice/**'
      - '.github/workflows/cart.yaml'
jobs:
  call-build-scan-and-push-cartservice-image:
    uses: ./.github/workflows/reuseable-build-docker-image.yaml
    with:
      image_name: cartservice
      dockerfile_path: cartservice/src/Dockerfile
      context_path: cartservice/src
      tag: ${{ github.run_id }}
      trivy_severity: 'CRITICAL,HIGH'
    secrets:
      GHCR_TOKEN: ${{ secrets.TOKEN }}