name: BUILD SCAN PUSH AND UPDATE IMAGE FOR CHECKOUTSERVICE

on:
  push:
    branches:
      - main
    paths:
      - 'checkoutservice/**'
      - '.github/workflows/checkout.yaml'
jobs:
  call-build-scan-and-push-checkoutservice-image:
    uses: ./.github/workflows/reuseable-build-docker-image.yaml
    with:
      image_name: checkoutservice
      dockerfile_path: checkoutservice/Dockerfile
      context_path: checkoutservice
      tag: ${{ github.run_id }}
      trivy_severity: 'CRITICAL,HIGH'
    secrets:
      GHCR_TOKEN: ${{ secrets.TOKEN }}